steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Pull latest docker image'
  entrypoint: 'bash'
  args: ['-c', 'docker pull ${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Build image'
  args: [
      'build',
      '-t',
      '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:${SHORT_SHA}',
      '-t',
      '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:latest',
      '--cache-from',
      '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:latest',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push image to registry'
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:${SHORT_SHA}']

- name: 'ubuntu'
  id: 'Replace placeholders'
  entrypoint: 'bash'
  args:
  - "-c sed -i 's/VPC_PLACEHOLDER/${_VPC}/' run-service.yaml && sed -i 's/SA_PLACEHOLDER/${_SA}/' run-service.yaml"

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'Launch Cloud Deploy pipeline'
  entrypoint: 'gcloud'
  args:
    - deploy
    - releases
    - create
    - release-${SHORT_SHA}
    - --project=${_PROJECT_ID}
    - --region=${_LOCATION}
    - --delivery-pipeline=${_PIPELINE}
    - --images=offline-wp=${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:${SHORT_SHA}

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:${SHORT_SHA}'
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/offline-wp:latest'

options:
  logging: CLOUD_LOGGING_ONLY
