apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 1
        run.googleapis.com/vpc-access-connector: 'internal-net'
    spec:
      serviceAccountName: "cloud-run-account@jalal2024.iam.gserviceaccount.com"
      containers:
      - image: offline-wp
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1G"
        env:
        - name: DB_HOST
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_HOST
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_USER
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_PORT
        - name: DB_DATABASE
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_DATABASE
