apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 0
        autoscaling.knative.dev/maxScale: 10
        run.googleapis.com/vpc-access-connector: 'internal-net'
    spec:
      containers:
      - image: offline-wp
        env:
        - name: DB_HOST
          valueFrom:
              secretKeyRef:
                key: just-testing
                version: 1
