apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 1
        run.googleapis.com/vpc-access-connector: VPC_PLACEHOLDER
    spec:
      serviceAccountName: SA_PLACEHOLDER
      containers:
      - image: offline-wp
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1G"
        env:
        - name: DB_HOST
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_HOST
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_USER
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_PASSWORD
        - name: DB_PORT
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_PORT
        - name: DB_DATABASE
          valueFrom:
              secretKeyRef:
                key: 1
                name: DB_DATABASE
        - name: SSP_GITHUB_TOKEN
          valueFrom:
              secretKeyRef:
                key: 1
                name: SSP_GITHUB_TOKEN
        - name: SSP_GITHUB_USER
          valueFrom:
              secretKeyRef:
                key: 1
                name: SSP_GITHUB_USER
        - name: SSP_GITHUB_REPO
          valueFrom:
              secretKeyRef:
                key: 1
                name: SSP_GITHUB_REPO
        - name: SSP_GITHUB_BRANCH
          valueFrom:
              secretKeyRef:
                key: 1
                name: SSP_GITHUB_BRANCH
        - name: DOMAIN_FUNCTION_URL
          valueFrom:
              secretKeyRef:
                key: 1
                name: DOMAIN_FUNCTION_URL
        - name: SERVICE_NAME
          valueFrom:
              secretKeyRef:
                key: 1
                name: SERVICE_NAME
        - name: WP_USER
          valueFrom:
              secretKeyRef:
                key: 1
                name: WP_USER
        - name: WP_EMAIL
          valueFrom:
              secretKeyRef:
                key: 1
                name: WP_EMAIL
        - name: WP_PASSWORD
          valueFrom:
              secretKeyRef:
                key: 1
                name: WP_PASSWORD
