apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 0
        autoscaling.knative.dev/maxScale: 5
    spec:
      containers:
      - image: offline-wp
